# Generated by Django 4.2.10 on 2024-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('state', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Штат')),
                ('works_day', models.IntegerField(blank=True, null=True, verbose_name='Рабочие дни')),
                ('fact_dat', models.IntegerField(blank=True, null=True, verbose_name='Факт рабочего дня')),
                ('ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Коэффициент')),
                ('tariff_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Тарифная ставка')),
                ('raising', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Повышение 100 %')),
                ('base_rate', models.IntegerField(blank=True, null=True, verbose_name='Основная ставка')),
                ('week_1_4', models.IntegerField(blank=True, null=True, verbose_name='Недельная нагрузка с 1 по 4')),
                ('week_5_9', models.IntegerField(blank=True, null=True, verbose_name='Недельная нагрузка с 5 по 9')),
                ('week_10_11', models.IntegerField(blank=True, null=True, verbose_name='Недельная нагрузка с 10 по 11')),
                ('home_learn_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Домашнее обучение - 1')),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итог')),
                ('base_salary', models.IntegerField(blank=True, null=True, verbose_name='Основная зарплата')),
                ('skip_lesson', models.IntegerField(blank=True, null=True, verbose_name='Пропущенные уроки')),
                ('amount_1', models.IntegerField(blank=True, null=True, verbose_name='Сумма 1 ')),
                ('replace_lesson', models.IntegerField(blank=True, null=True, verbose_name='Замена урока')),
                ('amount_2', models.IntegerField(blank=True, null=True, verbose_name='Сумма 2')),
                ('position_salary_1', models.IntegerField(blank=True, null=True, verbose_name='Должностной оклад - 1')),
                ('position_salary_2', models.IntegerField(blank=True, null=True, verbose_name='Должностной оклад - 2')),
                ('total_result', models.IntegerField(blank=True, null=True, verbose_name='Всего начисление')),
                ('ecology', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Экология 20 %')),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Надбавка 10 % ')),
                ('hazard_1', models.IntegerField(blank=True, null=True, verbose_name='Вредность - 1')),
                ('hazard_2', models.IntegerField(blank=True, null=True, verbose_name='Вредность - 2')),
                ('total_amount_1', models.IntegerField(blank=True, null=True, verbose_name='Соммасы 1 - 11 д/т')),
                ('total_amount_2', models.IntegerField(blank=True, null=True, verbose_name='Соммасы 1 - 11 д/т')),
                ('classroom_teach', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('classroom_salary_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='зп кл.руководство - 1')),
                ('classroom_salary_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='зп кл.руководство - 2')),
                ('home_learn_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Домашнее обучение - 2')),
                ('home_learn_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Домашнее обучение - 3')),
                ('lesson_room_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='пән кабинет - 1')),
                ('lesson_room_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='пән кабинет - 2')),
                ('update', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обнавленка')),
                ('three_languages_1', models.IntegerField(blank=True, null=True, verbose_name='три языка физ-ра - 1')),
                ('three_languages_2', models.IntegerField(blank=True, null=True, verbose_name='три языка физ-ра - 2')),
                ('master_1', models.IntegerField(blank=True, null=True, verbose_name='Магистр - 1')),
                ('master_2', models.IntegerField(blank=True, null=True, verbose_name='Магистр - 2')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='процент')),
                ('category_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Категория 1 процент')),
                ('category_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Категория 2 процент')),
                ('head_teacher_1', models.IntegerField(blank=True, null=True, verbose_name='Завуч надбавка - 1')),
                ('head_teacher_2', models.IntegerField(blank=True, null=True, verbose_name='Завуч надбавка - 2')),
            ],
        ),
    ]
